### PR TITLE
Fixed a syntax error in a_actor.idl and added it to make file. Added actor related constants.

### PR DESCRIPTION
**Pull request by ikkentim**
I had built the project without any errors, yet I found out I had made some errors in a_actor.idl, then realized I hadn't found them before because I didn't add a_actor.idl to the make file 
:fearful: 

Fixed all errors introduced in the previous pull request in this pull request.

### CODE REVIEW

**Comment by ikkentim** [comment]
I also forgot to add the INVALID_ACTOR_ID constant :(

**Comment by Zeex** [comment]
Wow, I didn't even notice you had a bad syntax there, I guess I'd make a terrible code reviewer. 

Could you also please move a_actors.inc to the beginning of the list in CMakeLists.txt while you're at it, to keep the files in alphabetical order?

**Comment by ikkentim** [comment]
Will do when I'm at my computer.

**Comment by Zeex** [comment]
No worries, I can do that myself. Thanks again.

**Pull request merged**
