### PR TITLE
added timer owner management in plugins

### PR DESCRIPTION
**Pull request by grasmanek94**

### CODE REVIEW

**Comment by grasmanek94** [comment]
As for the "failed" build it's because the example plugins need to be updated because, like I said.. issue #135

**Comment by grasmanek94** [comment]
Okay so I just added SetTimerEx which has the parameter 'owner' and left SetTimer unchanged (without owner paramter).

**Comment by Zeex** [comment]
Couldn't you make a map with timer IDs as the keys owners as the values instead of this? I mean, why add this to the library? Would it be of any use to others?

I'm asking this because It really seems useful only for debugging your particular bug. BTW have you managed to fix it yet?

**Comment by grasmanek94** [comment]
Well the issue occurs much less, though still happens that timers just don't fire.

**Comment by grasmanek94** [comment]
@Zeex if you want it, check it out: https://github.com/grasmanek94/eXe/
You could isolate the timer issue into these 3 files:
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/MiniGameSystem.hxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/MiniGameSystem.cxx
https://github.com/grasmanek94/eXe/blob/master/src/gamemode/MiniGameDerby.cxx

Other minigames are affected too.

**Comment by Zeex** [comment]
I can't merge this, however I created a new branch [timer-owner](https://github.com/Zeex/sampgdk/tree/timer-owner) just in case it would be useful in the future.

If you or somebody want to use you'll need to merge the timer-owner branch into master:

```sh
git merge timer-owner
```

or checkout timer-owner and merge with master:

```sh
git checkout timer-owner
git merge master
```

**Comment by grasmanek94** [comment]
Thank you very much! :D

**Pull request closed without merging**
